# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GotGam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GotGam
  pod 'Alamofire'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Action'
  pod 'RxDataSources'
  pod 'CenteredCollectionView'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'GoogleSignIn'

end
